services:
  redis_manager:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app_net

  db_manager:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis:
