services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app_net

  database:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - app_net

  app:
    image: dictionary:1.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - database
    environment:
      NODE_ENV: production
      DB_PASSWORD: mysecretpassword
      PORT: 3000
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis:
